### ISSUE TITLE
Deriving `Default` on type containing `IndexSet<T>` requires `T: Default`

### ISSUE THREAD

**Issue by linclelinkpart5** [bluss/indexmap#122] opened 2020-05-27 21:09 UTC
The following code fails to compile:

```rust
pub struct Data;

#[derive(Default)]
pub struct Newtype<T>(indexmap::IndexSet<T>);

fn test() {
    let _: Newtype<Data> = Default::default();
}
```

The error I observe is the following (this is in a module called 'types.rs'):

```
error[E0277]: the trait bound `types::Data: std::default::Default` is not satisfied
 --> src/types.rs:8:28
  |
8 |     let _: Newtype<Data> = Default::default();
  |                            ^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `types::Data`
  |
  = note: required because of the requirements on the impl of `std::default::Default` for `types::Newtype<types::Data>`
  = note: required by `std::default::Default::default`
```
However, adding the `#[derive(Default)]` to `Data` fixes the issue.

I am surprised that the automatic derive of `Default` requires that the data type stored in the `IndexSet` also be `Default`! It doesn't seem to make sense in this case.

**Comment by cuviper** [comment] 2020-05-27 21:16
See https://github.com/rust-lang/rust/issues/26925 -- the builtin derivations on anything with generic parameters also requires the same trait for each of those parameters. In fact that's why `IndexSet<T>` itself has to manually implement `Default`, otherwise it would rather just derive to the default of its inner `IndexMap`.

**Comment by bluss** [comment] 2020-05-28 00:00
Thanks. Closing since it's a general Rust issue (or no issue at all / works as intended) and not related to indexmap. You'll find the same issue with `Vec<T>`, for example.

**Closed by bluss** 2020-05-28 00:00 UTC
